[package]
name = "multiarch-debug"
version = "0.1.0"
authors = ["pzhxbz <pzhxbz@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "1.0"
goblin = "0.4"
zip = "0.5.12"
nix = "0.20.0"